User Interface III - Austin Walela
walela/UI-III-Flexbox pull request #1
Opened 2019-08-07 11:35 UTC by walela

test review comment

2019-08-07 14:58 UTC, walela commented
submitted first final version. Please review and give feedback.

2019-08-08 03:28 UTC, josenriagu reviewed
Hey Austin,
I am unable to preview your work. However, you do not worry, We will have a look at it together during 1;1 today.

Cheers!!

2019-08-08 03:53 UTC, josenriagu requested changes
Great job Austin!

You are almost there! At the same time;
• always keep a close eye on the design document. You have some elements spilling over the border. check here: https://prnt.sc/opui0h

Cheers!! keep it up

2019-08-08 03:53 UTC, josenriagu commented on great-idea/css/index.css
> +	align-content: space-between;
You probably are trying to leave some spaces between these two elements in the **subheader** div. To make it work you need just;

**justify-content: space-between**
and
**align-items: center**

please fix!

2019-08-18 09:11 UTC, merged